[package]
name = "projectm-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Safe Rust wrapper for libprojectM"

[dependencies]
projectm-sys = { path = "../projectm-sys" }
thiserror.workspace = true
tracing.workspace = true
